
###
GET http://localhost:8080/api HTTP/1.1

###
POST http://localhost:8080/api/ HTTP/1.1
Content-Type: application/json

{
    "nombre": "Mayra",
    "pass": "Capgemini",
    "correo": "mayra1@gmail.com",
    "tipo": 2
}

###
DELETE http://localhost:8080/api/1 HTTP/1.1

###
PUT http://localhost:8080/api/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Mayra Huante",
    "pass": "Capgemini",
    "correo": "mayra@gmail.com",
    "tipo": 2
}